name: Sync Juejin Articles

on:
  schedule:
    # 每天凌晨 2 点运行
    - cron: '0 2 * * *'

jobs:
  sync-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Call Sync Juejin Articles API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X GET "https://blog.vaebe.cn/api/articles/syncJuejinArticles" -H "x-api-key: $API_KEY"
